version: "3"
services:
  dbservice:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=manash@12345@
      - MYSQL_PASSWORD=manash@12345@
      - MYSQL_USERNAME=root
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306:3306
    networks:
      - artcart

  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/artcart_db?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=manash@12345@
      - spring.hibernate.show-sql=true
    ports:
      - 7002:7002
    networks:
      - artcart
networks:
  artcart:
